stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: rain000/hungrycat:latest

before_script:
  - docker info

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
    - docker push $DOCKER_IMAGE
  only:
    - main